# Generated by Django 5.2.6 on 2025-11-25 06:22

from decimal import Decimal
from django.db import migrations, models


def copy_daily_rate_to_tiers(apps, schema_editor):
    Car = apps.get_model("rentals", "Car")
    for car in Car.objects.all():
        rate = car.daily_rate
        car.rate_1_4_high = rate
        car.rate_5_14_high = rate
        car.rate_15_plus_high = rate
        car.rate_1_4_low = rate
        car.rate_5_14_low = rate
        car.rate_15_plus_low = rate
        car.save(
            update_fields=[
                "rate_1_4_high",
                "rate_5_14_high",
                "rate_15_plus_high",
                "rate_1_4_low",
                "rate_5_14_low",
                "rate_15_plus_low",
            ]
        )


class Migration(migrations.Migration):

    dependencies = [
        ("rentals", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="rate_15_plus_high",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="15+ days, high season (вс).",
                max_digits=8,
            ),
        ),
        migrations.AddField(
            model_name="car",
            name="rate_15_plus_low",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="15+ days, low season (нс).",
                max_digits=8,
            ),
        ),
        migrations.AddField(
            model_name="car",
            name="rate_1_4_high",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="1-4 days, high season (вс).",
                max_digits=8,
            ),
        ),
        migrations.AddField(
            model_name="car",
            name="rate_1_4_low",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="1-4 days, low season (нс).",
                max_digits=8,
            ),
        ),
        migrations.AddField(
            model_name="car",
            name="rate_5_14_high",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="5-14 days, high season (вс).",
                max_digits=8,
            ),
        ),
        migrations.AddField(
            model_name="car",
            name="rate_5_14_low",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="5-14 days, low season (нс).",
                max_digits=8,
            ),
        ),
        migrations.RunPython(copy_daily_rate_to_tiers, migrations.RunPython.noop),
    ]
