# Generated by Django 5.2.6 on 2025-11-25 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rentals", "0002_car_rate_15_plus_high_car_rate_15_plus_low_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="sts_issue_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="car",
            name="sts_issued_by",
            field=models.CharField(
                blank=True, help_text="Кем выдано СТС.", max_length=120, null=True
            ),
        ),
        migrations.AddField(
            model_name="car",
            name="sts_number",
            field=models.CharField(
                blank=True,
                help_text="Registration certificate (СТС) number.",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="car",
            name="vin",
            field=models.CharField(
                blank=True, help_text="VIN / номер кузова.", max_length=50, null=True
            ),
        ),
    ]
