# Generated by Django 5.2.6 on 2025-11-25 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "rentals",
            "0003_car_sts_issue_date_car_sts_issued_by_car_sts_number_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="customer",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="passport_issue_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="passport_issued_by",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="passport_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="passport_series",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="registration_address",
            field=models.TextField(
                blank=True, help_text="Адрес прописки / регистрации.", null=True
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="residence_address",
            field=models.TextField(
                blank=True, help_text="Адрес фактического проживания.", null=True
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                help_text="Гибкие теги, например VIP, проблемный, корпоративный.",
                related_name="customers",
                to="rentals.customertag",
            ),
        ),
    ]
