# Generated by Django 5.2.6 on 2025-11-25 19:52

import random

from django.db import migrations, models


def seed_contract_numbers(apps, schema_editor):
    Rental = apps.get_model("rentals", "Rental")
    seen = set(
        Rental.objects.exclude(contract_number__isnull=True)
        .exclude(contract_number="")
        .values_list("contract_number", flat=True)
    )

    def make_unique():
        for _ in range(100):
            candidate = f"{random.randint(10000, 99999):05d}"
            if candidate in seen:
                continue
            if Rental.objects.filter(contract_number=candidate).exists():
                continue
            seen.add(candidate)
            return candidate
        raise RuntimeError("Could not generate unique contract numbers during migration.")

    rentals = Rental.objects.filter(models.Q(contract_number__isnull=True) | models.Q(contract_number=""))
    for rental in rentals:
        rental.contract_number = make_unique()
        rental.save(update_fields=["contract_number"])


class Migration(migrations.Migration):

    dependencies = [
        ("rentals", "0004_customertag_customer_notes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rental",
            name="contract_number",
            field=models.CharField(
                blank=True,
                help_text="Автоматически сгенерированный 5-значный номер договора.",
                max_length=5,
                null=True,
                unique=True,
            ),
        ),
        migrations.RunPython(seed_contract_numbers, migrations.RunPython.noop),
    ]
