# Generated by Django 5.2.6 on 2025-11-25 20:57

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rentals", "0005_rental_contract_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="rental",
            name="airport_fee_end",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Сбор при возврате в аэропорту.",
                max_digits=8,
            ),
        ),
        migrations.AddField(
            model_name="rental",
            name="airport_fee_start",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Сбор при выдаче в аэропорту.",
                max_digits=8,
            ),
        ),
        migrations.AddField(
            model_name="rental",
            name="balance_due",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Сумма к оплате после предоплаты.",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="rental",
            name="booster_count",
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name="rental",
            name="child_seat_count",
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name="rental",
            name="crossbars_count",
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name="rental",
            name="delivery_issue_city",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="rental",
            name="delivery_issue_fee",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=Decimal("0.00"), max_digits=9
            ),
        ),
        migrations.AddField(
            model_name="rental",
            name="delivery_return_city",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="rental",
            name="delivery_return_fee",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=Decimal("0.00"), max_digits=9
            ),
        ),
        migrations.AddField(
            model_name="rental",
            name="discount_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=Decimal("0.00"), max_digits=9
            ),
        ),
        migrations.AddField(
            model_name="rental",
            name="discount_percent",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=Decimal("0.00"), max_digits=5
            ),
        ),
        migrations.AddField(
            model_name="rental",
            name="end_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="rental",
            name="night_fee_end",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Ночной выход при возврате.",
                max_digits=8,
            ),
        ),
        migrations.AddField(
            model_name="rental",
            name="night_fee_start",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Ночной выход при выдаче.",
                max_digits=8,
            ),
        ),
        migrations.AddField(
            model_name="rental",
            name="prepayment",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=Decimal("0.00"), max_digits=9
            ),
        ),
        migrations.AddField(
            model_name="rental",
            name="roof_box_count",
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name="rental",
            name="ski_rack_count",
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name="rental",
            name="start_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="rental",
            name="unique_daily_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Уникальный тариф по сделке. Перебивает цену авто.",
                max_digits=8,
                null=True,
            ),
        ),
    ]
