# Generated by Django 5.2.6 on 2025-11-25 21:17

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rentals", "0006_rental_airport_fee_end_rental_airport_fee_start_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rental",
            name="booster_included",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="rental",
            name="child_seat_included",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="rental",
            name="crossbars_included",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="rental",
            name="equipment_manual_total",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Фиксированная сумма за оборудование (если не по суткам).",
                max_digits=9,
            ),
        ),
        migrations.AddField(
            model_name="rental",
            name="roof_box_included",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="rental",
            name="ski_rack_included",
            field=models.BooleanField(default=False),
        ),
    ]
