# Generated by Django 5.1.6 on 2026-01-22 10:18

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rentals", "0010_rental_second_driver"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="car",
            options={"verbose_name": "Автомобиль", "verbose_name_plural": "Автомобили"},
        ),
        migrations.AlterModelOptions(
            name="contracttemplate",
            options={
                "verbose_name": "Шаблон договора",
                "verbose_name_plural": "Шаблоны договоров",
            },
        ),
        migrations.AlterModelOptions(
            name="customer",
            options={"verbose_name": "Клиент", "verbose_name_plural": "Клиенты"},
        ),
        migrations.AlterModelOptions(
            name="customertag",
            options={
                "ordering": ["name"],
                "verbose_name": "Тег клиента",
                "verbose_name_plural": "Теги клиентов",
            },
        ),
        migrations.AlterModelOptions(
            name="rental",
            options={"verbose_name": "Аренда", "verbose_name_plural": "Аренды"},
        ),
        migrations.AlterField(
            model_name="car",
            name="color",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Цвет"
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="daily_rate",
            field=models.DecimalField(
                decimal_places=2, max_digits=8, verbose_name="Базовый тариф, ₽/сутки"
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="fuel_tank_cost_rub",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Стоимость полного бака, ₽",
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="fuel_tank_volume_liters",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Объем бака, л"
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активен"),
        ),
        migrations.AlterField(
            model_name="car",
            name="loss_alloy_wheel_fee",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Диски алюмин",
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="loss_car_keys_fee",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Ключи от автомобиля",
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="loss_child_seat_fee",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Детское сидение",
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="loss_external_antenna_fee",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Внешняя радиоантенна или зонт",
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="loss_fire_extinguisher_fee",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Огнетушитель",
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="loss_first_aid_kit_fee",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Аптечка",
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="loss_gps_fee",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Навигатор",
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="loss_hubcaps_fee",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Декоративные колпаки",
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="loss_jack_fee",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Домкрат",
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="loss_license_plate_fee",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Гос. номера",
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="loss_radio_panel_fee",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Съемная панель магнитолы",
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="loss_reflective_vest_fee",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Светоотражающий жилет",
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="loss_registration_certificate_fee",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Свидетельство о регистрации ТС",
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="loss_ski_mount_fee",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Крепление лыж",
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="loss_steel_wheel_fee",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Диски сталь",
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="loss_tire_fee",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Автопокрышка",
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="loss_warning_triangle_fee",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Знак аварийной остановки",
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="make",
            field=models.CharField(max_length=50, verbose_name="Марка"),
        ),
        migrations.AlterField(
            model_name="car",
            name="model",
            field=models.CharField(max_length=50, verbose_name="Модель"),
        ),
        migrations.AlterField(
            model_name="car",
            name="photo_url",
            field=models.URLField(
                blank=True, max_length=500, null=True, verbose_name="Фото (ссылка)"
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="plate_number",
            field=models.CharField(max_length=20, unique=True, verbose_name="Госномер"),
        ),
        migrations.AlterField(
            model_name="car",
            name="rate_15_plus_high",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="15+ дней, высокий сезон (вс).",
                max_digits=8,
                verbose_name="15+ дней (высокий сезон)",
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="rate_15_plus_low",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="15+ дней, низкий сезон (нс).",
                max_digits=8,
                verbose_name="15+ дней (низкий сезон)",
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="rate_1_4_high",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="1-4 дня, высокий сезон (вс).",
                max_digits=8,
                verbose_name="1-4 дня (высокий сезон)",
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="rate_1_4_low",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="1-4 дня, низкий сезон (нс).",
                max_digits=8,
                verbose_name="1-4 дня (низкий сезон)",
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="rate_5_14_high",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="5-14 дней, высокий сезон (вс).",
                max_digits=8,
                verbose_name="5-14 дней (высокий сезон)",
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="rate_5_14_low",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="5-14 дней, низкий сезон (нс).",
                max_digits=8,
                verbose_name="5-14 дней (низкий сезон)",
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="region_code",
            field=models.CharField(
                blank=True,
                help_text="Регион номера (например, 26 или 82).",
                max_length=10,
                null=True,
                verbose_name="Регион",
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="registration_certificate_info",
            field=models.CharField(
                blank=True,
                help_text="Статус/комментарий по свидетельству о регистрации.",
                max_length=255,
                null=True,
                verbose_name="Свидетельство о регистрации",
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="security_deposit",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Залог по автомобилю.",
                max_digits=10,
                null=True,
                verbose_name="Залог",
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="sts_issue_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Дата выдачи СТС"
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="sts_issued_by",
            field=models.CharField(
                blank=True,
                help_text="Кем выдано СТС.",
                max_length=120,
                null=True,
                verbose_name="Кем выдана СТС",
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="sts_number",
            field=models.CharField(
                blank=True,
                help_text="Номер свидетельства о регистрации (СТС).",
                max_length=50,
                null=True,
                verbose_name="Номер СТС",
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="vin",
            field=models.CharField(
                blank=True,
                help_text="ВИН / номер кузова.",
                max_length=50,
                null=True,
                verbose_name="ВИН",
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="year",
            field=models.PositiveIntegerField(verbose_name="Год выпуска"),
        ),
        migrations.AlterField(
            model_name="contracttemplate",
            name="body_html",
            field=models.TextField(
                blank=True, null=True, verbose_name="Разметка веб-шаблона"
            ),
        ),
        migrations.AlterField(
            model_name="contracttemplate",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="contracttemplate",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="contract_templates/",
                verbose_name="Файл",
            ),
        ),
        migrations.AlterField(
            model_name="contracttemplate",
            name="format",
            field=models.CharField(
                choices=[
                    ("html", "Веб-шаблон"),
                    ("docx", "Документ Ворд"),
                    ("pdf", "ПДФ-форма"),
                ],
                default="html",
                max_length=10,
                verbose_name="Формат",
            ),
        ),
        migrations.AlterField(
            model_name="contracttemplate",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="contracttemplate",
            name="placeholder_help",
            field=models.TextField(
                default="Используйте {{ клиент.фио }}, {{ авто.госномер }}, {{ аренда.дата_начала }} и т.д.",
                verbose_name="Подсказка плейсхолдеров",
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="address",
            field=models.TextField(blank=True, null=True, verbose_name="Адрес"),
        ),
        migrations.AlterField(
            model_name="customer",
            name="birth_date",
            field=models.DateField(
                blank=True,
                help_text="Дата рождения.",
                null=True,
                verbose_name="Дата рождения",
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="discount_percent",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Персональная скидка, %.",
                max_digits=5,
                null=True,
                verbose_name="Скидка, %",
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="driving_since",
            field=models.DateField(
                blank=True,
                help_text="Дата начала стажа вождения (Стаж с ...).",
                null=True,
                verbose_name="Стаж с",
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="Эл. почта"
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="full_name",
            field=models.CharField(max_length=100, verbose_name="ФИО"),
        ),
        migrations.AlterField(
            model_name="customer",
            name="license_issued_by",
            field=models.CharField(
                blank=True,
                help_text="Кем выдано водительское удостоверение.",
                max_length=255,
                null=True,
                verbose_name="Кем выдано ВУ",
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="license_number",
            field=models.CharField(max_length=50, verbose_name="Номер ВУ"),
        ),
        migrations.AlterField(
            model_name="customer",
            name="notes",
            field=models.TextField(blank=True, null=True, verbose_name="Примечания"),
        ),
        migrations.AlterField(
            model_name="customer",
            name="passport_issue_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Дата выдачи паспорта"
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="passport_issued_by",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Кем выдан паспорт"
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="passport_number",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Номер паспорта"
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="passport_series",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Серия паспорта"
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="phone",
            field=models.CharField(max_length=30, verbose_name="Телефон"),
        ),
        migrations.AlterField(
            model_name="customer",
            name="registration_address",
            field=models.TextField(
                blank=True,
                help_text="Адрес прописки / регистрации.",
                null=True,
                verbose_name="Адрес прописки",
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="residence_address",
            field=models.TextField(
                blank=True,
                help_text="Адрес фактического проживания.",
                null=True,
                verbose_name="Адрес проживания",
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                help_text="Гибкие теги, например ВИП, проблемный, корпоративный.",
                related_name="customers",
                to="rentals.customertag",
                verbose_name="Теги",
            ),
        ),
        migrations.AlterField(
            model_name="customertag",
            name="name",
            field=models.CharField(
                max_length=50, unique=True, verbose_name="Название тега"
            ),
        ),
        migrations.AlterField(
            model_name="rental",
            name="airport_fee_end",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Сбор при возврате в аэропорту.",
                max_digits=8,
                verbose_name="Сбор аэропорт (возврат)",
            ),
        ),
        migrations.AlterField(
            model_name="rental",
            name="airport_fee_start",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Сбор при выдаче в аэропорту.",
                max_digits=8,
                verbose_name="Сбор аэропорт (выдача)",
            ),
        ),
        migrations.AlterField(
            model_name="rental",
            name="balance_due",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Сумма к оплате после предоплаты.",
                max_digits=10,
                verbose_name="К оплате",
            ),
        ),
        migrations.AlterField(
            model_name="rental",
            name="booster_count",
            field=models.PositiveIntegerField(
                blank=True, default=0, verbose_name="Кол-во бустеров"
            ),
        ),
        migrations.AlterField(
            model_name="rental",
            name="booster_included",
            field=models.BooleanField(default=False, verbose_name="Бустер"),
        ),
        migrations.AlterField(
            model_name="rental",
            name="car",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="rentals.car",
                verbose_name="Автомобиль",
            ),
        ),
        migrations.AlterField(
            model_name="rental",
            name="child_seat_count",
            field=models.PositiveIntegerField(
                blank=True, default=0, verbose_name="Кол-во детских кресел"
            ),
        ),
        migrations.AlterField(
            model_name="rental",
            name="child_seat_included",
            field=models.BooleanField(default=False, verbose_name="Детское кресло"),
        ),
        migrations.AlterField(
            model_name="rental",
            name="contract_number",
            field=models.CharField(
                blank=True,
                help_text="Автоматически сгенерированный 5-значный номер договора.",
                max_length=5,
                null=True,
                unique=True,
                verbose_name="Номер договора",
            ),
        ),
        migrations.AlterField(
            model_name="rental",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Создал",
            ),
        ),
        migrations.AlterField(
            model_name="rental",
            name="crossbars_count",
            field=models.PositiveIntegerField(
                blank=True, default=0, verbose_name="Кол-во поперечин"
            ),
        ),
        migrations.AlterField(
            model_name="rental",
            name="crossbars_included",
            field=models.BooleanField(default=False, verbose_name="Поперечины"),
        ),
        migrations.AlterField(
            model_name="rental",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="rentals.customer",
                verbose_name="Клиент",
            ),
        ),
        migrations.AlterField(
            model_name="rental",
            name="daily_rate",
            field=models.DecimalField(
                decimal_places=2, max_digits=8, verbose_name="Суточный тариф"
            ),
        ),
        migrations.AlterField(
            model_name="rental",
            name="delivery_issue_city",
            field=models.CharField(
                blank=True,
                default="",
                max_length=120,
                verbose_name="Город выдачи (доставка)",
            ),
        ),
        migrations.AlterField(
            model_name="rental",
            name="delivery_issue_fee",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=9,
                verbose_name="Стоимость выдачи",
            ),
        ),
        migrations.AlterField(
            model_name="rental",
            name="delivery_return_city",
            field=models.CharField(
                blank=True,
                default="",
                max_length=120,
                verbose_name="Город возврата (доставка)",
            ),
        ),
        migrations.AlterField(
            model_name="rental",
            name="delivery_return_fee",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=9,
                verbose_name="Стоимость возврата",
            ),
        ),
        migrations.AlterField(
            model_name="rental",
            name="discount_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=9,
                verbose_name="Скидка, ₽",
            ),
        ),
        migrations.AlterField(
            model_name="rental",
            name="discount_percent",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=5,
                verbose_name="Скидка, %",
            ),
        ),
        migrations.AlterField(
            model_name="rental",
            name="end_date",
            field=models.DateField(verbose_name="Дата окончания"),
        ),
        migrations.AlterField(
            model_name="rental",
            name="end_time",
            field=models.TimeField(
                blank=True, null=True, verbose_name="Время окончания"
            ),
        ),
        migrations.AlterField(
            model_name="rental",
            name="equipment_manual_total",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Фиксированная сумма за оборудование (если не по суткам).",
                max_digits=9,
                verbose_name="Фикс. сумма оборудования",
            ),
        ),
        migrations.AlterField(
            model_name="rental",
            name="night_fee_end",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Ночной выход при возврате.",
                max_digits=8,
                verbose_name="Ночной выход (возврат)",
            ),
        ),
        migrations.AlterField(
            model_name="rental",
            name="night_fee_start",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Ночной выход при выдаче.",
                max_digits=8,
                verbose_name="Ночной выход (выдача)",
            ),
        ),
        migrations.AlterField(
            model_name="rental",
            name="prepayment",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=9,
                verbose_name="Предоплата",
            ),
        ),
        migrations.AlterField(
            model_name="rental",
            name="roof_box_count",
            field=models.PositiveIntegerField(
                blank=True, default=0, verbose_name="Кол-во автобоксов"
            ),
        ),
        migrations.AlterField(
            model_name="rental",
            name="roof_box_included",
            field=models.BooleanField(default=False, verbose_name="Автобокс"),
        ),
        migrations.AlterField(
            model_name="rental",
            name="ski_rack_count",
            field=models.PositiveIntegerField(
                blank=True, default=0, verbose_name="Кол-во креплений"
            ),
        ),
        migrations.AlterField(
            model_name="rental",
            name="ski_rack_included",
            field=models.BooleanField(default=False, verbose_name="Крепления для лыж"),
        ),
        migrations.AlterField(
            model_name="rental",
            name="start_date",
            field=models.DateField(verbose_name="Дата начала"),
        ),
        migrations.AlterField(
            model_name="rental",
            name="start_time",
            field=models.TimeField(blank=True, null=True, verbose_name="Время начала"),
        ),
        migrations.AlterField(
            model_name="rental",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Черновик"),
                    ("active", "Активна"),
                    ("completed", "Завершена"),
                    ("cancelled", "Отменена"),
                ],
                default="draft",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="rental",
            name="total_price",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Итоговая сумма"
            ),
        ),
        migrations.AlterField(
            model_name="rental",
            name="unique_daily_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Уникальный тариф по сделке. Перебивает цену авто.",
                max_digits=8,
                null=True,
                verbose_name="Уникальный тариф, ₽/сутки",
            ),
        ),
    ]
