# Generated by Django 5.1.6 on 2026-01-23 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rentals", "0011_alter_car_options_alter_contracttemplate_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rental",
            name="operation_regions",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Регионы эксплуатации, разделённые запятыми.",
                verbose_name="Территория эксплуатации",
            ),
        ),
        migrations.AddField(
            model_name="rental",
            name="mileage_limit_km",
            field=models.PositiveIntegerField(
                choices=[(0, "0"), (200, "200"), (250, "250"), (300, "300")],
                default=0,
                verbose_name="Ограничение пробега, км",
            ),
        ),
    ]
