# Generated by Django 5.1.6 on 2026-01-23 00:00

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rentals", "0012_rental_operation_regions_and_mileage_limit"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rental",
            name="airport_fee_start",
        ),
        migrations.RemoveField(
            model_name="rental",
            name="airport_fee_end",
        ),
        migrations.AddField(
            model_name="rental",
            name="car_wash_fee",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=Decimal("1000.00"),
                help_text="Стоимость мойки автомобиля.",
                max_digits=8,
                verbose_name="Мойка",
            ),
        ),
    ]
