# Generated by Django 5.1.6 on 2026-01-23 00:00

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rentals", "0013_replace_airport_with_car_wash"),
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessSettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "high_season_start",
                    models.DateField(
                        blank=True,
                        help_text="Используются только день и месяц (год игнорируется).",
                        null=True,
                        verbose_name="Начало высокого сезона",
                    ),
                ),
                (
                    "high_season_end",
                    models.DateField(
                        blank=True,
                        help_text="Используются только день и месяц (год игнорируется).",
                        null=True,
                        verbose_name="Конец высокого сезона",
                    ),
                ),
                (
                    "car_wash_default",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1000.00"),
                        max_digits=8,
                        verbose_name="Мойка по умолчанию, ₽",
                    ),
                ),
                (
                    "night_fee_default",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=8,
                        verbose_name="Ночной выход по умолчанию, ₽",
                    ),
                ),
                (
                    "night_fee_slots_text",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Одна строка = один интервал. Пример: 20:00-23:59=1700",
                        verbose_name="Ночные интервалы (HH:MM-HH:MM=сумма)",
                    ),
                ),
                (
                    "child_seat_daily",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("200.00"),
                        max_digits=8,
                        verbose_name="Детское кресло, ₽/сутки",
                    ),
                ),
                (
                    "child_seat_cap",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("2800.00"),
                        max_digits=8,
                        verbose_name="Детское кресло, максимум ₽",
                    ),
                ),
                (
                    "booster_daily",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("100.00"),
                        max_digits=8,
                        verbose_name="Бустер, ₽/сутки",
                    ),
                ),
                (
                    "booster_cap",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1000.00"),
                        max_digits=8,
                        verbose_name="Бустер, максимум ₽",
                    ),
                ),
                (
                    "ski_rack_daily",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("400.00"),
                        max_digits=8,
                        verbose_name="Крепления для лыж, ₽/сутки",
                    ),
                ),
                (
                    "autobox_daily",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("900.00"),
                        max_digits=8,
                        verbose_name="Автобокс, ₽/сутки",
                    ),
                ),
                (
                    "crossbars_daily",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("300.00"),
                        max_digits=8,
                        verbose_name="Поперечины, ₽/сутки",
                    ),
                ),
                (
                    "delivery_fees_text",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Одна строка = один город. Можно указывать только изменения к базовому прайсу.",
                        verbose_name="Тарифы доставки (Город=сумма)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Настройки бизнеса",
                "verbose_name_plural": "Настройки бизнеса",
            },
        ),
    ]
