# Generated by Django 5.1.6 on 2026-01-24 00:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("rentals", "0014_business_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Дата добавления",
            ),
            preserve_default=False,
        ),
    ]
