# Generated by Django 5.1.6 on 2026-01-24

from django.db import migrations, models


OLD_PLACEHOLDER_HELP = "Используйте {{ клиент.фио }}, {{ авто.госномер }}, {{ аренда.дата_начала }} и т.д."
NEW_PLACEHOLDER_HELP = "Используйте {{ customer.full_name }}, {{ car.plate_number }}, {{ rental.start_date }} и т.д."


def update_placeholder_help(apps, schema_editor):
    ContractTemplate = apps.get_model("rentals", "ContractTemplate")
    ContractTemplate.objects.filter(placeholder_help=OLD_PLACEHOLDER_HELP).update(
        placeholder_help=NEW_PLACEHOLDER_HELP
    )


class Migration(migrations.Migration):

    dependencies = [
        ("rentals", "0015_customer_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contracttemplate",
            name="placeholder_help",
            field=models.TextField(
                default=NEW_PLACEHOLDER_HELP,
                verbose_name="Подсказка плейсхолдеров",
            ),
        ),
        migrations.RunPython(update_placeholder_help, migrations.RunPython.noop),
    ]
